---
title: Demo
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: posts
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: pages
    type: pages
  values:
    layout: page
permalink: pretty
